Facets:
  title: 'desc_metadata__title_ssim'
  creator: 'desc_metadata__creator_ssim'
  description: 'desc_metadata__description_ssim'

Show:
  title: 'desc_metadata__title_ssim'
  creator: 'desc_metadata__creator_ssim'
  description: 'desc_metadata__description_ssim'
  view: 'desc_metadata__view_ssim'
  provenance: 'desc_metadata__provenance_ssim'
  temporal: 'desc_metadata__temporal_ssim'
  location: 'desc_metadata__location_label_ssim'

Index:
  creator: 'desc_metadata__creator_ssim'
  description: 'desc_metadata__description_ssim'
