Facets:
  creator: 'desc_metadata__creator_label_sim'
  photographer: 'desc_metadata__photographer_label_sim'
  style period: 'desc_metadata__stylePeriod_label_sim'
  work type: 'desc_metadata__workType_label_sim'
  region: 'desc_metadata__location_label_sim'
  rights: 'desc_metadata__rights_label_sim'
  format: 'desc_metadata__format_label_sim'
  decade: 'date_decade_ssim'

Index:
  creator: 'desc_metadata__creator_sim'
  material: 'desc_metadata__material_ssm'
  date: 'desc_metadata__temporal_ssm'

Exceptions:
  ["reviewed_ssim", "has_thumbnail_bs", "system_create_dtsi", "system_modified_dtsi",
   "object_state_ssi", "active_fedora_model_ssi", "id", "object_profile_ssm", 
   "read_access_group_ssim", "workflow_metadata__reviewed_ssm", 
   "workflow_metadata__reviewed_ssim", "workflow_metadata__has_thumbnail_ssm", 
   "workflow_metadata__has_thumbnail_ssim", "desc_metadata__title_ssim", 
   "desc_metadata__title_tesim", "desc_metadata__photographer_ssm", 
   "desc_metadata__description_tesim", "desc_metadata__location_ssm", 
   "desc_metadata__type_ssm", "desc_metadata__format_ssm", "has_model_ssim", 
   "sort_date_desc_dtsi", "sort_date_asc_dtsi", "timestamp", "desc_metadata__rights_ssm", 
   "desc_metadata__set_ssm", "desc_metadata__lat_ssm", "desc_metadata__long_ssm", 
   "coords_ssim", "desc_metadata__creator_ssm", "date_decades_ssim", "desc_metadata__latitude_ssm", "desc_metadata__longitude_ssm", "desc_metadata__set_label_ssm", "desc_metadata__creator_label_ssm","coords_ssim", "desc_metadata__creator_ssm", "date_decades_ssim", 'desc_metadata__type_label_ssim']
