Facets:
  title: 'desc_metadata__title_ssim'
  creator: 'desc_metadata__creator_label_sim'
  photographer: 'desc_metadata__photographer_label_sim'
  style period: 'desc_metadata__style_period_sim'
  location: 'desc_metadata__location_label_sim'
  date: 'desc_metadata__date_sim'
  rights: 'desc_metadata__rights_label_sim'
  material: 'desc_metadata__material_sim'
  institution: 'desc_metadata__institution_sim'
  citation: 'desc_metadata__citation_sim'

Show:
  title: 'desc_metadata__title_ssm'
  creator: 'desc_metadata__creator_ssm'
  description: 'desc_metadata__description_ssm'
  view: 'desc_metadata__view_ssm'
  provenance: 'desc_metadata__provenance_ssm'
  temporal: 'desc_metadata__temporal_ssm'
  location: 'desc_metadata__location_label_ssm'

Index:
  creator: 'desc_metadata__creator_ssm'
  description: 'desc_metadata__description_ssm'
