Contact:
  tag_attributes:
    type: text
    class: tinymce
    default: ""
About:
  tag_attributes:
    type: text
    class: tinymce
    default: ""

Help:
  tag_attributes: 
    type: text
    class: tinymce
    default: ""
